const Application_Constant = {
    color_green_code:'#01A2C4',
    light_color:'#CAD0D6',
    skipText:'Sauter',
    Reparer_devient_facile_Text:'Réparer devient facile',
    Lorem_Ipsum_text:'Lorem Ipsum, giving information on its origins, as well as a random Lipsum.',
    now_save_text:'Maintenant, économisez votre temps',
    mobile_login_text:'Se connecter avec un téléphone portable',
    email_login_text:'Se connecter avec une adresse mail',
    register_free_text:'Inscrivez-vous gratuitement maintenant!',
    register_text:'S\'inscrire',
    password_text:'Mot de passe',
    email_address_text:'Adresse mail',
    forgotpassword_text:"Mot de passe oublié ?",
    new_coplete_text:'S\'inscrire sur Hop Assist',
    telephone_text:'Telephone',
    identificant_text:'Identificant',
    re_enter_pass_text:'Saisir a nouveau le mot de passe',
    prenom_text:'Prénom',
    Nom_de_familee:'Nom de familee',
    Addresse_text:   "Addresse",
    Anniversarie_text:  ' Anniversarie',
    Homme_text:'Référence',
    Moyen_text: 'Moyen de paiement',
    Type_de_client_text:'Choisir une catégorie',
    Particulier_text:    'Auto-Entrepreneur',
    Entreprise_text:     'Entreprise',
    categoty_req_text:'Catégorie (obligatoire)',
    Abbonement_text:'Abbonement',
    Clienten_compte_text:   'Client en compte',
    Sélectionnezun_avatar_text:   ' Sélectionnez un avatar',
    Ajouter_une_photo_text: 'Ajouter une photo',
    Prendre_votre_photo_text: 'Prendre votre photo',
    J_accepte_les_text: 'J accepte les',
    term_cinditions: ' termes et conditions',
    hop_assist:' d Hop assist',
    Inscrire_Maintenant_text:' Inscrire Maintenant',
    Veuillez_remplir_text: 'Veuillez remplir les champs obligatoires pour continuer',
    Adresse_de_dépannage_text:'Adresse de dépannage',
    Complement_De_Adresse_text:'Complement De Adresse',
    Quelle_text:'Quelle Est La Panne', 
    Veuillez_indiquer_text:'Veuillez indiquer les informations permettsnt a notre expert d\'intervenir chez vous',
    street_text:'Rue',
    zip_code_text:'Code postal',
    city_text:'Ville',
    door_code_text:'Code porte',
    floor_level_text:'Etage',
    other_text:'Autres',
    next_text:'Suivant',
    cancel_text:'Annuler',
    Magasins_disponibles:'Magasins disponibles',
    Quel_est_text:'Quel est l\'appareil concerné ?',
    createReservation_text:'Créer une demande de réservation',
    je_souhaite_text:'Je souhaite être entretenu(e)',
    À_partir_de_text:'À partir de',
    le_text:'Le',
    Aidez_nous_text:'Aidez-nous à comprendre votre problème',
    wait_aduio_photo_text:'Par écrit  et/ou  par audio et/ou  par photo',
    dites_nous_text:'Dites-nous quelle est votre demande :',
    
}
export default Application_Constant;