const Application_Constant = {
    color_green_code:'#01A2C4',
    light_color:'#CAD0D6',
    skipText:'Sauter',
    notificatiin_text:'Notifications',
    Reparer_devient_facile_Text:'Réparer devient facile',
    Lorem_Ipsum_text:'Lorem Ipsum, giving information on its origins, as well as a random Lipsum.',
    now_save_text:'Maintenant, économisez votre temps',
    mobile_login_text:'Se connecter avec un téléphone portable',
    email_login_text:'Se connecter avec une adresse mail',
    register_free_text:'Inscrivez-vous gratuitement maintenant!',
    register_text:'S\'inscrire',
    password_text:'Mot de passe',
    email_address_text:'Adresse mail',
    forgotpassword_text:"Mot de passe oublié ?",
    new_coplete_text:'S\'inscrire sur Hop Assist',
    telephone_text:'Telephone',
    identificant_text:'Identificant',
    re_enter_pass_text:'Saisir a nouveau le mot de passe',
    prenom_text:'Prénom',
    Nom_de_familee:'Nom de familee',
    Addresse_text:   "Addresse",
    Anniversarie_text:  ' Anniversarie',
    Homme_text:'Référence',
    Moyen_text: 'Moyen de paiement',
    reference_no_text:'Votre numéro de référence',
    Type_de_client_text:'Choisir une catégorie',
    Particulier_text:    'Auto-Entrepreneur',
    Entreprise_text:     'Entreprise',
    categoty_req_text:'Catégorie (obligatoire)',
    Abbonement_text:'Abbonement',
    Clienten_compte_text:   'Client en compte',
    Sélectionnezun_avatar_text:   ' Sélectionnez un avatar',
    Ajouter_une_photo_text: 'Ajouter une photo',
    Prendre_votre_photo_text: 'Prendre votre photo',
    J_accepte_les_text: 'J accepte les',
    term_cinditions: ' termes et conditions',
    hop_assist:' d Hop assist',
    Inscrire_Maintenant_text:' Inscrire Maintenant',
    Veuillez_remplir_text: 'Veuillez remplir les champs obligatoires pour continuer',
    Adresse_de_dépannage_text:'Adresse de dépannage',
    Complement_De_Adresse_text:'Complement De Adresse',
    Quelle_text:'Quelle Est La Panne', 
    Veuillez_indiquer_text:'Veuillez indiquer les informations permettsnt a notre expert d\'intervenir chez vous',
    street_text:'Rue',
    zip_code_text:'Code postal',
    city_text:'Ville',
    door_code_text:'Code porte',
    floor_level_text:'Etage',
    other_text:'Autres',
    next_text:'Suivant',
    cancel_text:'Annuler',
    Magasins_disponibles:'Magasins disponibles',
    Quel_est_text:'Quel est l\'appareil concerné ?',
    createReservation_text:'Créer une demande de réservation',
    je_souhaite_text:'Je souhaite être entretenu(e)',
    À_partir_de_text:'À partir de',
    le_text:'Le',
    Aidez_nous_text:'Aidez-nous à comprendre votre problème',
    wait_aduio_photo_text:'Par écrit  et/ou  par audio et/ou  par photo',
    dites_nous_text:'Dites-nous quelle est votre demande :',
    online_offline_text:'Vous êtes hors ligne maintenant Aller en ligne pour accepter les commandes',
    total_des_text:'Total des commandes',
    Mensuel_text:'Mensuel',
    Hebdomadaire_text:'Hebdomadaire',
    Benefice_total:'Bénéfice total',
    selection_le_text:'Sélectionner le mois',
    e_export_text:'L\'Export confirme être hors Ligne',
    etrs_vous_text:'Etrs -vous sur d\'etire en  pause ?',
    return_text:'RETOUR',
    confirm_text:'CONFIRME',
    newIntervention_text:'NOUVELLE INTERVENTION',
    new_intervention_string_text:'Hey {{$user.user first_name}}, Hopassist a une commande pour toil  Bonjour, Mr Nom Prénom Hop Assist a une intervention à te proposer! Ce travail sera disponible tant que l’util isateur ne choisit pas un autre expert. Vous pouvez vérifi er cette demande d’interventiondansvosnotificationsta nt qu’elleseradisponible.',
    Verifier_Maintenant_text:'Verifier Maintenant',
    Verifier_plus_tard_text:'Verifier plus tard',
    Details_du_service_text:'Details du service',
    accepter_text:'Accepter',
    Supprimer_text:'Supprimer',
    Commande_acceptée_text:'Commande acceptée',
    Felications_text:'Felications Hardley Peter',
    vous_etes_text:'vous êtes sélectionné pour effectuer l\'intervention demandée par hattaway anne',
    Intervention_prevue_à_text:'Intervention prevue à',
    Problème_rencontré_text:'Problème rencontré' ,
    Numero_de_la_text:'Numero de la commande',
    Lieu_text:'Lieu',
    Veuillez_text:' Veuillez indiquer votre heure d\'arrivée et être ponctuel.',
    Annuler_la_Commande_text:'Annuler la Commande',
    pourquoi_text:'Pourquoi voulez-vous annuler ce travail?',
    l_est_pas_text:'L\'utilisateur n\'est pas a la destination',
    l_reserve_text:'L\'utilisateur a reserve la mauvaise categorie',
    l_payer_text:'L\'utilisateur ne peut payer en especes Maintenant',
    Contretemps_text:'Contretemps',
    Estimation_text:'Estimation Du Travail',
    veuillez_creer_text:'Veuillez creer une estimation du cout du materiel a soumettre a l utilisateur.',
    frais_de_text:'Frais de connexion d\'hopassist',
    devis_text:'Devis Coût supplémentaire',
    Soumettre_text:'Soumettre',
    Requête_acceptée:'Requête acceptée',
    Hey_Hardley_Peter_text:'Hey  Hardley Peter',
    Votre_estimation_text:'Votre estimation est acceptée',
    accept_john_text:'John Smith a accepte ta comnanda .pret a commencer maintenat?',
    Commencez_text:'Commencez à travailler maintenant',
    Destination_text:'Destination atteinte',
    Vous_êtes_arrivé_text:'Vous êtes arrivé à destination',
    Cliquez_text:'Cliquez ICI Quand le travail est terminé',
    avis_text:'Avis De L\'utilisateur',
    ou_commenter_text:'Ou commenter',
    confirmer_text:'Confirmer',
    merci_text:'Merci d\'utiliser Hop Assist',
    Continuer_text:'Continuer',
    a_venir:'A venir',
    Historiques_text:'Historiques des interventions',
    my_profile:'Mon profil',
    mes_comptences_text:'Mes Categorie',
    devenir_text:'Devenir utilisateur',
    Notifications_text:'Notifications',
    faq_text:'FAQ',
    nous_contact_text:'Nous Contacter',
    logout_text:'Se déconnecter',
    Histoire_text:'Histoire',
    status_text:'Statut',
    numero_identification_text:'Numéro d\'identification du voyage',
    temp_de_text:'Temps de travail',
    category_text:'Categorie',
    mots_text:'Mots cles',
    commande_text:'Commande cree',
    l_intervention_text:'Historique de l\'intervention',
    information_text:'Information de la commande',
    contacts_text:'Contactez Nous',
    note_text:'Notre administrateur vérifiera les nouvelles commandes que vous avez ajoutes.',
    select_cat:'Choisissez une catégorie',

}
export default Application_Constant;